spring:
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_oa
      username: root
      password: root
  rabbitmq:
    host: localhost
    port: 5627
    username: guest
    password: guest
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/baike
  jpa:
    database: MySQL
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    org: warn
    com:
      youda: debug